"""belay/hooks/codex_adapter.py: normalize/render only (E18.5) -- see the
module's own docstring for why there's no live app-server wiring yet.
Fixture payloads below match the real shape of `ExecCommandApprovalParams`/
`ApplyPatchApprovalParams`/their `*Response` counterparts as generated by
`codex app-server generate-json-schema --experimental` against the actual
installed codex-cli 0.145.0 binary, not guessed from docs.
"""

from __future__ import annotations

import pytest
from belay.hooks.codex_adapter import (
    normalize_apply_patch_approval,
    normalize_exec_command_approval,
    render_apply_patch_approval_response,
    render_exec_command_approval_response,
)
from belay.hooks.gate import GateDecision, evaluate, evaluate_file_edit


def _exec_params(**overrides: object) -> dict:
    base = {
        "callId": "call_1",
        "command": ["git", "status"],
        "conversationId": "thread_abc",
        "cwd": "/repo-a",
        "parsedCmd": [],
    }
    base.update(overrides)
    return base


def _patch_params(**overrides: object) -> dict:
    base = {
        "callId": "call_2",
        "conversationId": "thread_abc",
        "fileChanges": {
            "/repo-a/f.txt": {"type": "update", "unified_diff": "@@ -1 +1 @@\n-a\n+b\n"}
        },
    }
    base.update(overrides)
    return base


class TestNormalizeExecCommandApproval:
    def test_argv_is_rejoined_into_a_shell_string(self) -> None:
        event = normalize_exec_command_approval(
            _exec_params(command=["git", "status"]),
            installation_id="i",
            host_session_id="thread_abc",
        )
        assert event.args["command"] == "git status"
        assert event.surface == "shell"
        assert event.tool_name == "Bash"
        assert event.host == "codex"

    def test_argv_with_spaces_is_quoted_not_misjoined(self) -> None:
        event = normalize_exec_command_approval(
            _exec_params(command=["rm", "-rf", "a file with spaces"]),
            installation_id="i",
            host_session_id="thread_abc",
        )
        # shlex.split must reconstruct the original three-element argv --
        # a naive " ".join would collapse the quoting information needed
        # to tell "one arg with spaces" from "three separate args".
        import shlex

        assert shlex.split(event.args["command"]) == ["rm", "-rf", "a file with spaces"]

    def test_call_id_becomes_the_event_id(self) -> None:
        event = normalize_exec_command_approval(
            _exec_params(callId="call_xyz"), installation_id="i", host_session_id="s"
        )
        assert event.event_id == "call_xyz"

    def test_trust_tier_is_unknown(self) -> None:
        event = normalize_exec_command_approval(
            _exec_params(), installation_id="i", host_session_id="s"
        )
        assert event.trust_tier == "UNKNOWN"

    def test_missing_command_raises(self) -> None:
        params = _exec_params()
        del params["command"]
        with pytest.raises(ValueError):
            normalize_exec_command_approval(params, installation_id="i", host_session_id="s")

    def test_non_string_command_items_raise(self) -> None:
        with pytest.raises(ValueError):
            normalize_exec_command_approval(
                _exec_params(command=["git", 123]), installation_id="i", host_session_id="s"
            )

    def test_the_normalized_event_actually_runs_through_the_real_gate(self) -> None:
        """End-to-end within this test process: a Codex-shaped approval
        request, once normalized, is indistinguishable to gate.evaluate()
        from a Claude Code one -- confirming the host-agnostic design."""
        from belay.approvals.queue import ApprovalQueue

        queue = ApprovalQueue()
        event = normalize_exec_command_approval(
            _exec_params(command=["git", "status"]), installation_id="i", host_session_id="s"
        )
        result = evaluate(event, queue)
        assert result.verdict == "allow"

        event2 = normalize_exec_command_approval(
            _exec_params(callId="call_danger", command=["rm", "-rf", "/tmp/x"]),
            installation_id="i",
            host_session_id="s",
        )
        result2 = evaluate(event2, queue)
        assert result2.verdict == "deny"
        assert len(queue.list()) == 1


class TestRenderExecCommandApprovalResponse:
    def test_allow_renders_the_bare_approved_string(self) -> None:
        assert render_exec_command_approval_response(
            GateDecision("allow", "belay: safe")
        ) == {"decision": "approved"}

    def test_deny_renders_a_structured_denied_decision_with_the_reason(self) -> None:
        out = render_exec_command_approval_response(GateDecision("deny", "belay: paused"))
        assert out == {"decision": {"denied": {"rejection": "belay: paused"}}}


class TestNormalizeApplyPatchApproval:
    def test_single_file_change_is_normalized_to_a_file_surface_event(self) -> None:
        event = normalize_apply_patch_approval(
            _patch_params(), installation_id="i", host_session_id="thread_abc"
        )
        assert event.surface == "file"
        assert event.tool_name == "Write"
        assert event.args["file_path"] == "/repo-a/f.txt"

    def test_multi_file_patch_picks_the_first_path_deterministically(self) -> None:
        params = _patch_params(
            fileChanges={
                "/repo-a/z.txt": {"type": "add", "content": "z"},
                "/repo-a/a.txt": {"type": "add", "content": "a"},
            }
        )
        event = normalize_apply_patch_approval(params, installation_id="i", host_session_id="s")
        assert event.args["file_path"] == "/repo-a/a.txt"  # sorted first, not dict order

    def test_empty_file_changes_raises(self) -> None:
        with pytest.raises(ValueError):
            normalize_apply_patch_approval(
                _patch_params(fileChanges={}), installation_id="i", host_session_id="s"
            )

    def test_the_normalized_event_runs_through_the_real_file_edit_gate(
        self, tmp_path
    ) -> None:
        from belay.approvals.queue import ApprovalQueue
        from belay.hooks.file_snapshot import SnapshotStore
        from sqlalchemy import create_engine

        target = tmp_path / "f.txt"
        target.write_text("original", encoding="utf-8")
        params = _patch_params(fileChanges={str(target): {"type": "update", "unified_diff": "x"}})
        event = normalize_apply_patch_approval(params, installation_id="i", host_session_id="s")

        queue = ApprovalQueue()
        engine = create_engine("sqlite:///:memory:", future=True)
        snapshots = SnapshotStore(engine, tmp_path / "snaps")
        result = evaluate_file_edit(event, queue, snapshots)
        assert result.verdict == "allow"
        snap = snapshots.get(event.event_id)
        assert snap is not None
        assert snap.existed_before is True


class TestRenderApplyPatchApprovalResponse:
    def test_allow_and_deny_match_exec_commands_shape(self) -> None:
        assert render_apply_patch_approval_response(
            GateDecision("allow", "belay: captured")
        ) == {"decision": "approved"}
        out = render_apply_patch_approval_response(GateDecision("deny", "belay: too big"))
        assert out == {"decision": {"denied": {"rejection": "belay: too big"}}}
